### ISSUE TITLE
Investigate GitHub's releases feature

### ISSUE THREAD

**Issue by LuPro** [LuPro/SlabelFish#14]
I wanna do some versioning/releases stuff that's more understandable/readable for outsiders/new users. Additionally to this I'd like to provide a precompiled self-contained program so people who don't have a dev environment set up can still use the tool (or set up a website with it running and a webinterface but that sounds like more work and I need a server for this)

**Comment by flofriday** [comment]
Your current solution (putting binaries into the git repo) might be a quick solution, but is generally considered bad-practice.

## The Trouble
1) DX (Developer Experience) might decrease as those binary blobs get bigger which means that simply cloning the repository might become a big bottleneck on slow networks. Keep in mind that git tracks the history of old files and this means that every time you clone this repo you also download all binary releases (yes there is some compression but still)
2) UX is not amazing because the users need git and again they have to download all old releases.
3) Yes you can rewrite history so that only the newest file is in the history but that is not trivial git usage and might be kinda difficult. (Also its a simple way to shoot yourself in the foot).
4) It makes collaboration much harder. Assume I have an idea for an amazing feature and enough time on my hands to implement it. So I work on it and you work on another feature. Everything is fine until we both merge our commits and git asks us which binary to keep. Unfortunately there is no way git can merge binaries. So the only way (I know) to fix this is to merge our changes and then create a new commit with a new binary that has both features.

## A Solution
Fortunately GitHub has a solution for this problem: [GitHub Releases](https://docs.github.com/en/repositories/releasing-projects-on-github/about-releases).
You can also look at one of my apps where I use releases heavily: [TU Addressbook](https://github.com/flofriday/TU_Wien_Addressbook)

## A personal note
I also sometimes put binaries or images into a repository, especially when I am the only intended user. But doing it right even for small projects builds good habits and maybe shows your future employer that you really know what you are doing 😉

**Comment by LuPro** [comment]
Yeah, i know putting them in the repo sucks, but I was lazy :P i intend to remove them once I've looked into that releases stuff but just wanted to get that behind me for now - thanks for the feedback :) I don't intend to build a new binary, so it'll stay at this one sin 😂
